### ISSUE TITLE
Issue with NuGet package (dependent package not available)

### ISSUE THREAD

**Issue by elylv** [amuste/BlGridExamples#1]
When attempting to install the NuGet package, I get error:
Unable to find package DnetOverlayComponent. No packages exist with this id in source(s): DevExpress, Microsoft Visual Studio Offline Packages, NuGet

I guess the DnetOverlayComponent package is not published in NuGet.

**Comment by amuste** [comment]
> I guess the DnetOverlayComponent package is not published in NuGet.

You're right. The package is published now

Let me know if you can install it now

**Comment by elylv** [comment]
Awesome, working now!  Thanks for the quick reply.
